name: MachinaDrill
version: 1.5
description: A Machina that moves forward and breaks blocks in its path.
author: Lyneira
main: me.lyneira.MachinaDrill.MachinaDrill
depend: [MachinaCraft]
permissions:
    machinadrill.*:
        description: Gives full access to using a drill, including deactivating another player's drill.
        children:
            machinadrill.activate: true
            machinadrill.deactivate-own: true
            machinadrill.deactivate-all: true
    machinadrill.activate:
        description: Allows activating a drill.
        default: op
    machinadrill.deactivate-own:
        description: Allows deactivating the player's own drill.
        default: op
    machinadrill.deactivate-all:
        description: Allows deactivating any drill.
        default: op